twitter:
  auth:
    consumer_key: <CONSUMER_KEY>
    consumer_secret: <CONSUMER_SECRET>
    access_token: <ACCESS_TOKEN>
    access_token_secret: <ACCESS_SECRET>
  jobs:
    rss_feed:
      enabled: True
      interval: 5
    tested:
      source:
        name: FHI
        url: https://www.fhi.no/sv/smittsomme-sykdommer/corona/dags--og-ukerapporter/dags--og-ukerapporter-om-koronavirus/
      enabled: True
      interval: 5
      text_pos_singular: ny registrert testet
      text_pos_plural: nye registrert testet
    tested_lab:
      source:
        name: FHI
        url: https://www.fhi.no/sv/smittsomme-sykdommer/corona/dags--og-ukerapporter/dags--og-ukerapporter-om-koronavirus/
      enabled: True
      interval: 5
    confirmed:
      source:
        name: MSIS
        url: https://statistikk.fhi.no/msis
      enabled: True
      interval: 5
      text_pos_singular: nytt registrert smittetilfelle
      text_pos_plural: nye registrerte smittetilfeller
      text_neg_singular:
      text_neg_plural:
    confirmed_by_testdate:
      source:
        name: FHI
        url: https://www.fhi.no/sv/smittsomme-sykdommer/corona/dags--og-ukerapporter/dags--og-ukerapporter-om-koronavirus/
      enabled: True
      interval: 5
    dead:
      source:
        name: FHI
        url: https://www.fhi.no/sv/smittsomme-sykdommer/corona/dags--og-ukerapporter/dags--og-ukerapporter-om-koronavirus/
      enabled: True
      interval: 5
      text_pos_singular: nytt dødsfall registrert
      text_pos_plural: nye dødsfall registrert
    hospitalized:
      enabled: True
      interval: 5
      source:
        name: Helsedirektoratet
        url: https://www.helsedirektoratet.no/statistikk/antall-innlagte-pasienter-pa-sykehus-med-pavist-covid-19
    vaccine:
      enabled: True
      interval: 5
      source:
        name: FHI
        url: https://www.fhi.no/sv/vaksine/koronavaksinasjonsprogrammet/koronavaksinasjonsstatistikk/
    smittestopp:
      enabled: True
      interval: 5
      source:
        name: FHI
        url: https://www.fhi.no/om/smittestopp/nokkeltall-fra-smittestopp/
